#Set to false to disable the default way of unlocking trinkets.
unlockEnabled = true
#Cooldown (ticks) between unlocks
#Range: 0 ~ 1728000
unlockCooldown = 2400
#List of banned trinkets eg: ["losttrinkets:piggy", "losttrinkets:magical_feathers"]
#The trinkets listed in here will also be removed from players that already unlocked them.
blackList = []
#List of trinkets that can't be unlocked randomly eg: ["losttrinkets:piggy", "losttrinkets:magical_feathers"]
#The trinkets listed in here will not be removed from players that already unlocked them.
nonRandom = [
"losttrinkets:broken_totem",
"losttrinkets:mad_aura",
"losttrinkets:magical_feathers",
"losttrinkets:magical_herbs",
"losttrinkets:ruby_heart",
"losttrinkets:glory_shards",
"losttrinkets:mirror_shard",
"losttrinkets:dark_egg",
"losttrinkets:coffee_bean",
"losttrinkets:tea_leaf",
"losttrinkets:ember",
"losttrinkets:drop_spindle",
"losttrinkets:dark_dagger",
"losttrinkets:dragon_breath",
"losttrinkets:fire_mind",
"losttrinkets:serpent_tooth",
"losttrinkets:wither_nail",
"losttrinkets:golden_melon",
"losttrinkets:book_o_enchanting",
"losttrinkets:tha_bat",
"losttrinkets:tha_wizard",
"losttrinkets:treble_hooks",
"losttrinkets:blaze_heart",
"losttrinkets:glass_shard",
"losttrinkets:tha_spider",
"losttrinkets:empty_amulet",
"losttrinkets:ice_shard",
"losttrinkets:turtle_shell",
"losttrinkets:tha_cloud",
"losttrinkets:rock_candy",
"losttrinkets:magneto",
"losttrinkets:creepo",
"losttrinkets:horseshoe",
"losttrinkets:mossy_belt",
"losttrinkets:mossy_ring"
]

[Trinket_Slots]
	#Amount of Xp levels added to the next unlocking cost.
	#Range: 0 ~ 1000
	slotUpFactor = 5
	#Maximum number of trinket slots the player can have (does not remove unlocked slots)
	#Range: 1 ~ 40
	maxSlots = 5
	#Numbers of trinket slots the player will start with (Only effect newer players!!).
	#Range: 0 ~ 40
	startSlots = 1
	#Levels of xp needed to unlock a trinket slot.
	#Range: 0 ~ 1000
	slotCost = 35

[Killing_Unlocks]
	#Set to false to disable unlocking trinkets from killing non-Boss entities.
	killingUnlockEnabled = false
	#Rarity of unlocking a trinket from killing non-Boss entities. (Greater number = more rare)
	#Range: 2 ~ 100000
	killing = 120

[Bosses_Killing_Unlocks]
	#Set to false to disable unlocking trinkets from killing Bosses.
	bossKillingUnlockEnabled = true
	#Rarity of unlocking a trinket from killing Bosses. (Greater number = more rare)
	#Range: 2 ~ 100000
	bossKilling = 10

[Farming_Unlocks]
	#Set to false to disable unlocking trinkets from farming.
	farmingUnlockEnabled = false
	#Rarity of unlocking a trinket from farming. (Greater number = more rare)
	#Range: 2 ~ 100000
	farming = 140

[Ores_Mining_Unlocks]
	#Rarity of unlocking a trinket from mining ores. (Greater number = more rare)
	#Range: 2 ~ 100000
	oresMining = 100
	#Set to false to disable unlocking trinkets from mining ores.
	oresMiningUnlockEnabled = false

[Trading_Unlocks]
	#Rarity of unlocking a trinket from trading. (Greater number = more rare)
	#Range: 2 ~ 100000
	trading = 170
	#Set to false to disable unlocking trinkets from trading.
	tradingUnlockEnabled = true

[Wood_Cutting_Unlocks]
	#Rarity of unlocking a trinket from cutting trees. (Greater number = more rare)
	#Range: 2 ~ 100000
	woodCutting = 170
	#Set to false to disable unlocking trinkets from cutting trees.
	woodCuttingUnlockEnabled = false

