
["Aileron Forge Config"]

	["Aileron Forge Config".Campfires]
		#Push players
		campfiresPushPlayers = true
		#Smoke Stack Charge Ticks
		smokeStackChargeTicks = 20

	["Aileron Forge Config".Fireworks]
		#Enable changes to fireworks
		doFireworkChanges = true

