
["Gameplay Settings"]
	#toggle experimental features, currently this option is unused and may be removed.
	useExperimentalGameplay = false

["World Generation Settings"]
	#toggle the glowsquid spawn, useful if you're using upgrade aquatic.
	spawnGlowsquids = false
	#toggle the copper ore generation, useful if you use other mods that spawn copper.
	useCopperGeneration = true
	#toggle the cave biome generation, not sure why would you want to do such thing but ok...
	useCaveBiomes = true
	#define the size for the cave biomes to be generated, by default it is 4.
	#Range: 1 ~ 10
	caveBiomeSize = 1

