
#General settings
[general]
	#Sets the percentage the mod checks for [default: 10] (1 to 100)
	#Range: 1 ~ 100
	Percentage = 10
	#Change this option to let it not display a chat message (if you have sound enabled) [default: true]
	SendMessage = true
	#Dictates if it should also actively check armor [default: false]
	CheckArmor = false
	#Change this option to change the color / formatting of the message (if you have messages enabled) [default: YELLOW]
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	SentMessageColor = "YELLOW"
	#Change this option to let it play a sound (configurable in the sound tab) [default: false]
	PlaySound = true

#Sound settings
[sound]
	#Change this option to change the color / formatting of the message (if you have sound enabled) [default: minecraft:block.note_block.pling]
	soundlocation = "minecraft:block.note_block.pling"
	#Sets the sound volume [default: 0.6] (0 to 1.0)
	#Range: 0.0 ~ 1.0
	volume = 0.6

