#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 12 15:46:30 CEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1.zip
enableShaders=true
