#Determines if the 'Coyote Time' feature is enabled.
#'Coyote Time' allows the player to jump for a second or two after falling off of a block in order to stop themselves from falling into a pit.
#This will not allow the player to double jump, only jump when walking off of a block.
coyoteTimeEnabled = true
#Determines how long (in ticks) the player has to jump with 'Coyote Time' after falling off a block.
#Range: > 1
coyoteTimeTicks = 10
#Determines if the 'Second Chance' feature is enabled.
#'Second Chance' leaves the player at half a heart after taking fatal damage from a mob or explosion while at or above 7 hearts.
secondChanceEnabled = true
#Determines if the 'Second Chance' sound will play when the effect is activated.
secondChanceSound = true
#Determines if the 'Second Chance' feature will be activated by explosions.
secondChanceExplosions = true
#Determines if the 'Second Chance' feature will be activated by mobs.
secondChanceMobs = true
#Determines how much health the player must start with for 'Second Chance' to activate.
#Range: 0.5 ~ 20.0
secondChanceActivationHealth = 13.5
#Determines how much health the player should be left with after 'Second Chance' activates.
#Range: 1.0 ~ 20.0
secondChanceHealthRemainder = 1.0

